### ISSUE TITLE
QuestDB using Gorm2

### ISSUE THREAD

**Issue by ultd** [questdb/questdb#1347]
**Is your feature request related to a problem? Please describe.**
I noticed gorm2 support was fixed/added 8 days ago with as mentioned in #1021. When do you expect for this to be released and work properly? Will it support all types (including `bytea`)?

**Comment by bsmth** [comment]
Hi @ultd thanks a lot for raising the issue. The ticket you mention was closed because it was a duplicate. Compatibility with gorm2 has an issue at https://github.com/questdb/questdb/issues/383 - if you would like to upvote, or add other ideas, you're welcome to do that there. I'll close this issue so that we have a single place to track compatibility

Thanks a lot 🙌🏻
