### ISSUE TITLE
Unable to insert data using line protocol if field value contains nested double quotes along with comma or space

### ISSUE THREAD

**Issue by arina-ielchiieva** [questdb/questdb#1415]
**To Reproduce**
1. Create table: 
```sql
create table column_values(
      device_id symbol index,
      values string,
      timestamp timestamp) 
timestamp(timestamp) partition by day
```

2. Insert data using line protocol:
```java
LineTCPProtoSender(...)
   .metric("column_values")
   .tag("device_id", "d1")
   .field("values", "{\"c1\":1,\"c2\":2}")
  .`$`(Os.currentTimeNanos())
```

Error:
```log
2021-10-08T12:37:12.992527Z E i.q.c.l.t.LineTcpConnectionContext [37] could not parse measurement, code INVALID_FIELD_VALUE at 72 line (may be mangled due to partial parsing) is column_values,device_id=d1 values="{"c1":1,"c2":2}" 1633696632977293000
```

If comma is replaced with space, the same error occurs:
```log
2021-10-08T12:40:28.275395Z E i.q.c.l.t.LineTcpConnectionContext [37] could not parse measurement, code INVALID_FIELD_VALUE at 71 line (may be mangled due to partial parsing) is column_values,device_id=d1 values="{"c1":1 "c2":2}" 1633696828242944000
```
The same data without space and comma (`"{"c1":1"c2":2}"`) is inserted successfully.

**Expected behavior**
Data is inserted.

**Environment**
 - Version: 6.0.7.1

**Comment by Rene-Roscher** [comment]
Hi everyone, have a similar problem....

I can't store more than 2 key value in my environment

Also used the line protocol with the following insert: (It's Work)
`lvk-ls,version=1.0.14 ads=aa ip_address=1.2.2 1639730570820000000`

But as soon as another parameter is added like in the following example, an error occurs in the console.
`lvk-ls,version=1.0.14 ads=aa ip_address=1.2.2 x=11 1639730570820000000`

`2021-12-17T08:47:32.720948Z E i.q.c.l.t.LineTcpConnectionContext [7] could not parse measurement, code INVALID_FIELD_SEPARATOR at -1 line (may be mangled due to partial parsing) is`

Can anyone tell me there if I am doing something wrong? Escaping doesn't help in this case either...

**Comment by glasstiger** [comment]
> Hi everyone, have a similar problem....
> 
> 
> 
> I can't store more than 2 key value in my environment
> 
> 
> 
> Also used the line protocol with the following insert: (It's Work)
> 
> `lvk-ls,version=1.0.14 ads=aa ip_address=1.2.2 1639730570820000000`
> 
> 
> 
> But as soon as another parameter is added like in the following example, an error occurs in the console.
> 
> `lvk-ls,version=1.0.14 ads=aa ip_address=1.2.2 x=11 1639730570820000000`
> 
> 
> 
> `2021-12-17T08:47:32.720948Z E i.q.c.l.t.LineTcpConnectionContext [7] could not parse measurement, code INVALID_FIELD_SEPARATOR at -1 line (may be mangled due to partial parsing) is`
> 
> 
> 
> Can anyone tell me there if I am doing something wrong? Escaping doesn't help in this case either...
> 
> 
> 
> QuestDB : 6.1.3

Hi Rene-Roscher,
Could you try to use comma as field separator, please?

Suggest to try the below:
lvk-ls,version=1.0.14 ads=aa,ip_address=1.2.2,x=11 1639730570820000000

Please, let me know if the above works.
