### ISSUE TITLE
Documentation doesn't include LEV for webconsole import

### ISSUE THREAD

**Issue by zacharywhitley** [questdb/questdb#150]
This isn't quite a feature request, or but report. Maybe a UX report? 

The documentation at https://www.questdb.io/docs/usingWebConsole doesn't say what the "LEV" button in the webconsole does. 

In addition it would be nice if there was a tool tip that told you what "A" "O", and "H" are. I know it's in the documentation but it was a little strange to have to look that up. I was hoping I could just mouse over and it would have told me. I was scratching my head for a little bit on that, "What the heck is "A", "O" and "H"?

Maybe there are tool tips and I'm just not seeing them. I'm running Firefox 68 on CentOS Linux

**Comment by bluestreak01** [comment]
thanks Zachary, we are looking into it

**Comment by bluestreak01** [comment]
'A' means 'Append', 'O' - overwrite, 'H' - header toggle, if on - this tells server that input file has header row. When 'H' is off - header row is detected automatically.

**Comment by zacharywhitley** [comment]
Thanks. I got that from the docs but what isn’t in the docs is what LEV is.

**Comment by TheTanc** [comment]
Hi, Zachary,
you are right, this option needs to be documented. Also the tooltip suggestion is great, we will implement.
`LEV` allows you to choose how to treat a file in case it has some random dangling extra columns that were not found upon schema detection. 
If `LEV` flag is set, rows with dangling columns will be completely skipped. Otherwise, the rows will be imported, and only the dangling value will be ignored.
I will release a much more detailed version of the web console documentation later today.
