### ISSUE TITLE
live demo dies on SQL: select * from 'trips' where fare_amount<15.0 order by pickup_datetime;

### ISSUE THREAD

**Issue by qlbit-com** [questdb/questdb#1707]
### Describe the bug

live demo dies on SQL
```
  select * from 'trips' where fare_amount<15.0 order by pickup_datetime;
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by ideoma** [comment]
Here `order by pickup_datetime` is redundant, data will be sorted by pickup_datetime by default because it's designated timestamp but SQL optimiser does not recognise this

**Comment by bluestreak01** [comment]
also, bear with us https://github.com/questdb/questdb/pull/1592

**Comment by bluestreak01** [comment]
> Here `order by pickup_datetime` is redundant, data will be sorted by pickup_datetime by default because it's designated timestamp but SQL optimiser does not recognise this

this is something we should fix in isolation

**Comment by bluestreak01** [comment]
`order by` erasure works as expected, the issue is predicate search that returns 1.3Bn rows. The issue of "dying" is timeout because SQL hit "cold" column that needs to be read from disk. Second pass should be in 30s range, which is still slow of course.

**Comment by qlbit-com** [comment]
same effect observed with:
   `select * from 'trips' where passenger_count=2;`
select without a predicate responds in milliseconds, though select with a predicate takes minutes or more for a db with 1.6mil records.
for any other tables, "forever true" predicate slows down dramatically.
like 
 `select * from 'pos' ; `
takes 1.5milliseconds
though
 `select * from 'pos' where lat<600;`  
takes 6.9 seconds.
**that is 6000 times slower.**
is that expected?

**Comment by bluestreak01** [comment]
It is expected, however there is PR in flight that might accelerate predicates up to 200x. I referenced this PR in an earlier comment

**Comment by bziobrowski** [comment]
Current demo timings (with JIT and multithreaded filter processing enabled) : 
```
select *
from trips 
where fare_amount<15.0 
order by pickup_datetime
```
4s  (returns 1302837790 rows)


`select * from trips where passenger_count=2;
1.5s  (returns 235 503 614)

If you add limit clause , e.g. limit 10000 then you can go well below 1s . 

As for "forver true" predicate slowing things down - 
- trips table contains 1634599313 records (so not 1.6mil but 1634 mil or 1.6 billion rows)
- QDB doesn't use constraints yet (except for symbols) so it can't prove (during planning/optimization) that such expressions are redundant and remove them 
-```sql 
select * from table 
```
is very different from 
```sql
select * from table where predicate 
```
because the former can start returning rows right away (and finish fast if there's limit clause) while the latter has to scan the data to find matching rows . If only matching rows happen to be at the end of table then db has to scan all of it and there could be arbitrarily large difference/speed up depending on table size .
