### ISSUE TITLE
Out-of-order data ingestion

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#172]
Support user-level timestamps arriving out of order.

Instead of rejecting out-of-order timestamps we will be able to insert delayed data in the middle of time series.

**Comment by PiotrDabkowski** [comment]
Even weaker version of this would be very useful - allowing unordered data, but with a constraint that it is still ordered within a particular symbol (or symbol combination).  

For example: we may have a symbol GOOG with timestamps 1, 2, 3 and FB and with timestamps 1, 2. It would be great to do an insert as follows: [GOOG 1], [GOOG 2], [GOOG 3], [FB 1], [FB 2]. Notice, data is still ordered within a symbol, [GOOG 2], [GOOG 1] would be considered invalid.
I guess this can be implemented much more efficiently than `inserting in the middle` as we can keep GOOG and FB in separate files and do appends (or otherwise).
If course I could have a separate table for each symbol, but this is not very convenient.

**Comment by bluestreak01** [comment]
this has been merged to master with #926 there outstanding bugs that we're fixing
