### ISSUE TITLE
implement `>` and `>=` functionality for Long256 types

### ISSUE THREAD

**Issue by EugeneTeu** [questdb/questdb#1904]
### Is your feature request related to a problem?

```sql
CREATE table test (
    a long256,
    b long256
)

insert INTO TEST (a,b) VALUES(0x94a942,0x94a942)

select * from test where a >= 0x94a942;
```

Right now this doesnt work, giving an error message

### Describe the solution you'd like.

`>` and other math operators should work on long256 values 

### Describe alternatives you've considered.

Casting as double but this loses precision

**Comment by puzpuzpuz** [comment]
As @marregui pointed out, long256 was originally added to represent crypto public addresses, so it lacks arithmetical operations support.

While we should certainly improve the docs, in order to implement this request, we might need to support missing arithmetical operations for long256. Some of our users were also requesting long128, so we could also consider adding this type.

**Comment by EugeneTeu** [comment]
@puzpuzpuz got it thanks for responding quickly

**Comment by huanghe-1** [comment]
i think  don't let one tsdb to do much more operation function，it need  focus on,  you can convert  0x94a942 to a really long 9,742,658 ,than to use where a>=9,742,658
