### ISSUE TITLE
Unrecognized VM option 'UseParallelOldGC' on JDK 17

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2058]
While trying to start  the  _Any (no JVM)_ QuestDB version on JDK 17 I have got the following error:

```
Unrecognized VM option 'UseParallelOldGC'
Did you mean '(+/-)UseParallelGC'? Error: Could not create the Java Virtual Machine.
```

```
$ java -version 
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
```

It's probably related to https://openjdk.java.net/jeps/366
The fix should be easy:  Use `-XX:+UseParallelGC` instead of `-XX:+UseParallelOldGC`. This switch will enable the parallel collector for both young and old generations.

**Comment by puzpuzpuz** [comment]
Looks like a duplicate of #1926

**Comment by jerrinot** [comment]
that's right!
closing as dup.

**Comment by marvin-hansen** [comment]
Why has this and #1926 has been closed without resolution? 

I have this issue, means, QuestDB fails to start on OSX with JDK 17 

The parallel collector was deprecated in JDK 9 and removed in JDK 10. 
https://bugs.openjdk.java.net/browse/JDK-8151084

The new default is the G1 collector and for any JDK version 9 and above would be

-XX:+UseG1GC

https://www.oracle.com/technetwork/tutorials/tutorials-1876574.html

All it takes to fix this problem is a simple version check of the JVM, and select the options relative to the detected JDK.

Do you think you can patch this problem or are there any other breaking changes implied that would required JDK V8?

**Comment by jerrinot** [comment]
Hi @marvin-hansen ,

This issue was fixed in the master branch: https://github.com/questdb/questdb/pull/1969/commits/1791521754abf5af27e0e7eb5c0ded259e06cc56
The fix will be included in the next release, which will be shipped soon.

**Comment by marvin-hansen** [comment]
Awesome,

thanks for the update!


Marvin Hansen
