### ISSUE TITLE
(QuestDB is not reachable [503]

### ISSUE THREAD

**Issue by shuitai** [questdb/questdb#2063]
### Describe the bug

select vendor_id, cab_type, sum(passenger_count)
from 'trips' 
group by vendor_id, cab_type
limit 10

run this sql query cannot get the result (QuestDB is not reachable [503])

### To reproduce

select vendor_id, cab_type, sum(passenger_count)
from 'trips' 
group by vendor_id, cab_type
limit 10

### Expected Behavior

get result, not 503

### Environment

```markdown
https://demo.questdb.io/
```

**Comment by HeZean** [comment]
Hi @shuitai,

Are you using a proxy like nginx, which may return 503 on timeout?

As I remember, QDB itself doesn't use code 503, but sometimes queries can be a bit slow (for example, all the cache misses), but you can retry once and get the result immediately.

**Comment by shuitai** [comment]
@HeZean 
please the query 
select vendor_id, cab_type, sum(passenger_count)
from 'trips'
group by vendor_id, cab_type
limit 10

in your demo page, you could reproduce it, if using clickhouse with 1 instance, similar data size, it could return result in several seconds.

**Comment by HeZean** [comment]
Hi @shuitai, thanks for the information you provided. As I tested, the `503` code was sent by the proxy of *demo.questdb.io* (timeout after 30sec), the frontend checks the status code and will display `QuestDB is not reachable` for any status code other than `200` or `400`.

The query does take an unbearably long time due to the `sum()` function, however. We can test for that on *demo.questdb.io*, with the same data size of 'trips'.
```sql
select count(*) from 'trips';  -- 1634599313
select x from long_sequence(1634599313);  -- execute: 208.42μs
select sum(x) from long_sequence(1634599313);  -- execute: 16.4s
```

I don't remember how other databases performance on `sum`, but QDB's one seems somehow needs to be optimized. Could you please, if wish, close this issue, and open another issue to help contributors notice and focus on `sum` function?

**Comment by HeZean** [comment]
Similar to #2052 [(comment)](https://github.com/questdb/questdb/issues/2052#issuecomment-1106596651)

**Comment by shuitai** [comment]
@HeZean 
I think the root cause is not sum() function, when group by multi columns( >=2 ) ( group by a, b), the query will cost lots of time.
So maybe questdb should optimize the groupby performance.

**Comment by HeZean** [comment]
@shuitai sorry for being lack of time for me to do a further research about it, but it would be awesome if you would like to do some benchmark.

(Not sure about whether the following examples could help, could you please try analyze them?)
```sql
select ls1.x, ls2.x
from long_sequence(1634599313) ls1
  cross join long_sequence(1634599313) ls2
group by ls1.x;  -- Execute: 309.44μs
```
```sql
select ls1.x, ls2.x
from long_sequence(1634599313) ls1
  cross join long_sequence(1634599313) ls2
group by ls1.x, ls2.x;  -- Execute: 358.08μs
```
```sql
select ls1.x, sum(ls2.x)  -- note the 'sum'
from long_sequence(1634599313) ls1
  cross join long_sequence(1634599313) ls2
group by ls1.x;  -- query timeout after 30s
```
