### ISSUE TITLE
QuestDB web console long type data display lost precision issues

### ISSUE THREAD

**Issue by misselvexu** [questdb/questdb#2088]
### Describe the bug

`questdb` console sql query display results in the processing of long type data display lost precision issues.

### To reproduce

None.

### Expected Behavior

- Web Console Execute Result .
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/3436472/166129490-9467e794-a0a8-413c-b44f-d4bcdc81f172.png">

- REST Api Execute Result .
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/3436472/166129462-1e075783-e562-4b76-a21d-7f887939064f.png">

### Environment

```markdown
- **QuestDB version**: 6.2.1
- **OS**: macOS 12.3.1 (21E258)
- **Browser**: Version 15.4 (17613.1.17.1.13)
```

### Additional context

None.

**Comment by HeZean** [comment]
Hi, I've checked the code, as far as I am concerned, the problem was JavaScript it self. After the frontend fetch the Json string response, it directly parse it, unfortunately, some results may out of the bound of `Number.MAX_SAFE_INTEGER` aka `9007199254740992`.

To solve this, we may need to implement (or use? QDB may not want to have much dependencies) functions similar to some 3rd-party lib like `LosslessJSON`.

ref: https://stackoverflow.com/questions/15689790/parse-json-in-javascript-long-numbers-get-rounded

**Comment by misselvexu** [comment]
So，What's next plan?😘

**Comment by HeZean** [comment]
@bluestreak01 thanks for the tip, that's quiet a brilliant approach! We don't even need to have js parse the number, and users won't care about what a long is actually been taken as (string or number).
So the only thing left for us is to add several `"` into the existing tests? If so, I'm willing to take several minutes to fix it.
