### ISSUE TITLE
Web Console executes next statement instead of the current one when the cursor is at the end position

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2151]
### Describe the bug

As simple as the following screenshot:
![web-console-cursor-issue](https://user-images.githubusercontent.com/37772591/170215641-89503b54-d914-46e5-a04d-95c502876625.png)
1

### Environment

```markdown
- **QuestDB version**: 6.3.1
- **OS**: Ubuntu 20.04 x64
- **Browser**: Chrome 101.0.4951.64 (Official Build) (64-bit)
```

**Comment by HeZean** [comment]
Hi, I'd like to fix it, but could you please point out whether we need a test for it? Or can I directly open a PR?

**Comment by insmac** [comment]
@HeZean 

Thanks for looking into this. There is no test suite within `questdb/questdb` repository, but you might want to look into this if you want:
https://github.com/questdb/ui/blob/main/packages/browser-tests/cypress/integration/console/editor.spec.js

We have a cypress spec sheet in a separate repository which runs across a set of common editor use cases. If you have experience with Cypress and are willing to contribute, don't hesitate to add a test there. Otherwise it's completely fine if you just publish a PR to the main repo directly.

**Comment by HeZean** [comment]
Hi @insmac, I tried running the tests, and got in touch with a new, inspiring testing framework (thanks for introducing it to me!)

However, there may be something wrong with my env that tests all got timeout and I'm afraid I cannot add a test by myself, without being able to pass it locally.

If you wish, a test case that that fully checks statement slicing may be added:
```sql
;;select 1;;;;;
select 2;   ;

select 3;;select
4


```
