### ISSUE TITLE
Infinit Loop

### ISSUE THREAD

**Issue by suoyi123wang** [questdb/questdb#2232]
### Describe the bug

There is infinit loop in method `searchValueBlock`  whose class is `io.questdb.cairo.BitmapIndexUtils`

### To reproduce

Here is the test case:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/44200574/173982543-5314479b-c6d2-4265-8876-485f444010f1.png">

Here is the source code:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/44200574/173982737-21ce3971-9cc8-4923-b2d7-a1500702a15d.png">
<img width="612" alt="image" src="https://user-images.githubusercontent.com/44200574/173982764-a4ca7cd0-0bc7-4608-aa34-59ba0d30b751.png">

And the return value of `memory.getLong(...)`  is always less than value.

**Comment by marregui** [comment]
Hi @suoyi123wang I hope you are well, thank you for the report.

This specific method is meant to search for `row id`, 100% guaranteed to exist, otherwise it means the index is corrupt.
Are you using an embedded index in your code?, if so, what is the use case?. If there is no use case, then I think I will throw an exception instead of retuning -1L.

Regards
