### ISSUE TITLE
SQL: `select * trades` should be parse error

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2294]
### To reproduce

1. go to (demo)[https://demo.questdb.io/]
2. query `select * trades`. Note of missing `FROM` keyword

One row with 1 returned

### Expected Behavior

SQL error

### Environment

```markdown
- **QuestDB version**: 6.4.2
```

**Comment by marregui** [comment]
Gets a T-Shirt when competed by a member of the community

**Comment by lookharm** [comment]
Hi @marregui , I want to contribute to this issue. Can I start working on this?

**Comment by marregui** [comment]
Hola @lookharm , yes please!. If you need help or get stuck, do let me know, here or in Slack :)

**Comment by lookharm** [comment]
Need help @marregui 
I found that `select *` and `select * table_y` will be accepted by the parser too even if a `table_y` doesn't exist on the database.

The bug is probably at a funciton`parseDml0`: https://github.com/questdb/questdb/blob/f7bcd5af33e8336d9eeed921eb97ddac1f545d50/core/src/main/java/io/questdb/griffin/SqlParser.java#L933-L965
The query like `select * trades ` or `select *` will be parsed by `parseSelectClause` (line 965) and terminate immediately without pass to the `parseFromClause` (line 965) because of `token == null`(line 941). I'm not sure what kinds of `SELECT` queries need no `FROM` clauses.

**Comment by marregui** [comment]
Hi @lookharm ,

Indeed you found the entry point into the issue.

In QuestDB you can navigate to the webconsole, type simply the table name and hit run. This acts as an `alias` for the full statement `select * from tab`. However the implementation has a whole and it also allows you (the bug) to do `select * tab`.
In the last case, the `*` is found and interpreted as an expression. The following token should be from, but it is not, instead it is the table name which is parsed as a literal. The parser does not care at the moment about the missing from.

But we can do better than that. The solution needs to support, as equivalent statements:

- select * from tab
- tab

And needs to report the message 'from' expected (something along these lines) and fail the query.

You could start by adding a test along the lines of:

```
@Test
    public void testSelectWildcardMissingFrom() throws SqlException {
        assertQuery(
                "select-choose tab.x x, tab.y y from (select [x, y] from tab)",
                "select * tab",
                modelOf("tab").col("x", ColumnType.INT).col("y", ColumnType.INT)
        );
    }
```

in class `SqlParserTest`. From there, it would be great to have a test also in `SqlCompilerTest`, and then possibly an additional test in `PGJobContextTest`.

You are on the right track!

**Comment by lookharm** [comment]
Hi @marregui ,
What about this test case: https://github.com/questdb/questdb/blob/f7bcd5af33e8336d9eeed921eb97ddac1f545d50/core/src/test/java/io/questdb/griffin/SqlParserTest.java#L4740-L4752

What is "<-- dangling 'select *'"? Is `select *` a correct syntax?

**Comment by lookharm** [comment]
A bit confusing about functions e.g `reader_pool` and `reader_pool()` both of them work perfectly even the first one has no parenthesis. And all of these too:
`select current_schema` and `select current_schema()` 
`select dump_memory_usage` and `select dump_memory_usage()` 
`select session_user` and `select session_user()` 

So what is the difference between the function and literal, how can we categorize it? Or should we clarify obviously the function must have parenthesis?

If I add `hasSeenLiteral` checking it will fail in case of a function that has no parenthesis eg. `select session_user` because `col.getAst().type` is `LITERAL`.

https://github.com/questdb/questdb/compare/master...lookharm:questdb:fix/2294
```java
hasSeenLiteral |= col.getAst().type == ExpressionNode.LITERAL;
if (tok == null && hasSeenLiteral) {
   throw err(lexer, tok, "'from' expected");
}
```

**Comment by marregui** [comment]
QuestDB's parser views SQL as a functional language. Some modern languages, like elixir, have parenthesis as optional, particularly when there are no parameters for the function. We work that way as well, so that when we see a literal, in a select clause, we treat it as a function.

Class `FunctionParser` has method `parseFunction`, if you put a breakpoint there you will see that as we traverse the AST, the literal is found to be a valid function.

As per `select *` ... well, as per the above.... hmmm, hmmm, it is a valid expression, which returns 1. This is because QuestDB produces a long_sequence (LongSequenceFunctionFactory) to select from, and this is a cursor that returns a single column (x) containing the current count. In fact it is exactly equivalent to `select * from long_sequence(1)`.

**Comment by lookharm** [comment]
Maybe this is not a bug, even if we use an alias for `*` it will not change column names. If we use this query: `select * x from 'gas_prices'` in the demo page it will return `timestamp` and `galon_price` same as `select * from 'gas_prices'` (x does not have an effect on column names). So the `select * tab` that returns `x` is probably right because `x` is the column name of `long_sequence`.

**Comment by marregui** [comment]
The semantics of the queries:

- `select * from tab`: You can think of tab as a cursor over the selected fields for table **tab**.
- `select *`: The parser injects ` from long_sequence(1)`, so now the cursor contains just one column, **x**, one row only.
- `select * tab`: This makes sense, but has been deemed ugly, and this issue is about not tolerating this syntax.

You could argue that because `select *` injects a from something, perhaps `select * tab` should too... but we deemed it ugly. It has to go, ugliness has no place in this repo :)

**Comment by marregui** [comment]
Hey @lookharm , thank you for the contribution!, please claim the black-belt T-shirt from https://docs.google.com/forms/d/e/1FAIpQLSfI3VUwXpHT1TbZYjUkYFQpuyfhWicWu2zA0NBGP0pO3ImITA/viewform 

Contributing to QuestDB makes it better!
