### ISSUE TITLE
Support PARTITION BY WEEK

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2297]
### Is your feature request related to a problem?

We have users periodically asking for week-based partitioning.

### Describe the solution you'd like.

Add WEEK to the PARTITION BY options.

### Additional context.

This PR should give enough hints on how to implement this feature: https://github.com/questdb/questdb/pull/1571

**Comment by puzpuzpuz** [comment]
@Diemarg sure thing. Assigned you to this issue. Look forward to seeing your contribution. 👍

**Comment by Belair34** [comment]
I've been looking at this issue to potentially use in a hackathon if Diemarg doesn't end up doing it. After adding all of the relevant sections based on the "Hours" PR linked above, it seems like I have it almost working. The problem is that it's always off by 1 week either in the INSERT (the resulting partition folder is wrong) or in the SELECT (the folder that it looks for is wrong). One of these is always correct, but the other is off by 1 week for some reason. Currently, I'm using the format "yyyy-w" because there was no OP_WEEK_OF_YEAR_TWO_DIGITS which was a bit concerning. Any advice on why this might be happening, or where I should look?

**Comment by puzpuzpuz** [comment]
@Belair34 I think the best approach would be to create a draft PR with your changes, so that we could follow up on the code. Hard to tell what may be lacking without seeing the code. WDYT?

**Comment by Belair34** [comment]
@puzpuzpuz My colleagues and I ended up making a bit of progress towards figuring out the issue. We found a small typo in this code: https://github.com/questdb/questdb/blob/b649f7e293d96740db4b111af4cbbf011cd4849d/core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java#L358-L360
where there was addition instead of subtraction as described by p(y) in this formula: https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_year
On Monday we can make a PR with the fix and some additional tests if we are correct about this.
We'll also create a draft around that time if we're still having any problems with the main issue.
Thanks for the timely response!
