### ISSUE TITLE
ALIGN TO CALENDAR feels buggy

### ISSUE THREAD

**Issue by javier** [questdb/questdb#2390]
### Describe the bug

`ALIGN TO CALENDAR` has a weird behaviour affecting to clauses like `FILL` or `LIMIT`. Maybe to some others, but I am guessing the fix is the same

### To reproduce

Two problems here: `LIMIT` and `FILL`

## LIMIT 
If I go to the demo site and execute this query, it works
```
select  last(price), `symbol` from trades
SAMPLE BY 1h limit 100
```

If I now add any modifiers to `SAMPLE BY,` it breaks
```
select  last(price), `symbol` from trades
SAMPLE BY 1h ALIGN to calendar limit 100
```

However, if I add a `TIME ZONE` and an `OFFSET`, it works. Note that if I add *only* a `TIME ZONE` is not enough and requires and offset even if it is zero. It seems like a parsing issue. This works

```
select  last(price), `symbol` from trades
SAMPLE BY 1h  ALIGN TO CALENDAR TIME ZONE 'Europe/Berlin'
WITH OFFSET '00:00' limit 10
```

I am aware I can use subqueries to do the limit on the outer query, but developer experience here is not great as I would expect `SAMPLE BY` and `LIMIT` either to work together or not, but not something in between

## FILL

This query works
```
select  last(price), `symbol` from trades
SAMPLE BY 1h FILL(PREV) ALIGN TO CALENDAR 
```

This query doesn't
```
select  last(price), `symbol` from trades
SAMPLE BY 1h  ALIGN TO CALENDAR  FILL(PREV)
```

No matter if I add time zone and offset. It still fails. It says `FILL` token is unexpected. Unless I am reading [the diagram at the docs wrong](https://questdb.io/docs/reference/sql/sample-by/), `FILL` can be used after a `SAMPLE BY` query

### Expected Behavior

`LIMIT` should work with `SAMPLE BY` or not, but consistently

FILL should be accepted after `ALIGN` clause according to the docs. Maybe this is just a docs issue

`TIME ZONE `and `WITH OFFSET` should be optional according to the docs, and according to the diagram at the website it seems `WITH OFFSET `shouldn't be accepted after `TIME ZONE`, but that's probably a fix for the documentation itself

### Environment

```markdown
- **QuestDB version**: 6.4.3
- **OS**: Linux
- **Browser**: Chrome
```

### Additional context

This is the architecture diagram [at the doc site](https://questdb.io/docs/reference/sql/sample-by/)

![image](https://user-images.githubusercontent.com/3839/182593625-2bb4f222-744e-4172-9e9d-e1637c0ad8b3.png)

**Comment by javier** [comment]
This is still nor working.

This query breaks, complaining a time zone and offset is needed

```SQL
SELECT
  FIRST(price) AS open,
  max(price) AS high,
  min(price) AS low,
  last(price) AS close,
  sum(amount) AS volume,
  timestamp as timestamp
FROM
  trades
where timestamp in '2022-11'  
SAMPLE BY 1s
FILL(PREV, PREV, PREV, PREV, 0) ALIGN TO CALENDAR 
limit 0,15
```

If I add the TZ and offset it works fine, but this should not be needed

```SQL
SELECT
  FIRST(price) AS open,
  max(price) AS high,
  min(price) AS low,
  last(price) AS close,
  sum(amount) AS volume,
  timestamp as timestamp
FROM
  trades
where timestamp in '2022-11'  
SAMPLE BY 1s
FILL(PREV, PREV, PREV, PREV, 0) ALIGN TO CALENDAR TIME ZONE 'Europe/Berlin' WITH OFFSET '00:00'
limit 0,15
```

**Comment by jerrinot** [comment]
Hello @javier,

According to the grammar at https://questdb.io/docs/reference/sql/sample-by/#syntax
when you align “to calendar” then either “time zone” or “with offset” is mandatory.
So one could say “working as designed” 🙈 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/158619/201309561-7619d05d-e0bc-40e0-9bda-5a8afeac9541.png">

Except it's not! 

As you noticed when a query ends with `align to calendar` then it works. Currently, it works merely accidentally. And it breaks when you add, e.g. limit after the `align to calendar`. 

Moreover - as you noticed, our documentation suggests that a `align to calendar` without timezone/offset should work:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/158619/201310262-fe5b2070-0f19-44c2-b66b-9213e2dc0db8.png">

So this example is inconsistent with our own published grammar. 

I would argue we should change the grammar so `align to calendar` defaults to `with offset '00:00` unless specified otherwise. Because that's what most users expect. 

So thank you for re-opening this issue; let's fix this for good!
