### ISSUE TITLE
Order by ignored when selecting from virtual table

### ISSUE THREAD

**Issue by Zahlii** [questdb/questdb#2465]
### Describe the bug

When selecting from a table created within the current statement, order by statements are ignored. While this is usually not a common use case, it makes it much more difficult to write certain tests.

### To reproduce

`select * from (select rnd_double() a, cast(rnd_boolean() as int) b from long_sequence(5)) order by b asc, a desc`

### Expected Behavior

Output now:

0.211188411394841	0
0.7052415793041816	1
0.34554687804047357	1
0.572948455300064	0
0.6288379799771233	1

Expected output:

0.572948455300064	0
0.211188411394841	0
0.7052415793041816	1
0.6288379799771233	1
0.34554687804047357	1

### Environment

```markdown
- **QuestDB version**: 6.5.1
- **OS**:
- **Browser**:
```

**Comment by Belair34** [comment]
I looked into this issue for a while before giving up so here are my main findings:
- The real issue is that order by doesn't work correctly with virtual records like rnd_double(), so a simpler query like the following can reproduce it: `select x, rnd_double() a from long_sequence(5) order by a asc`
- The reason this doesn't work is because the random doubles are first generated in the sorting process and are never stored in a way that works for the sorting. So in each iteration of the sort it basically generates 2 random doubles, compares them, and swaps them accordingly, and then in the next iteration it generates two new random doubles to compare rather than including one of the previous ones. This results in some random scrambling of the final output (Notice the random order of the Long x from the above query when compared to `select x from long_sequence(5)`)
- I think these are the relevant areas to look at:
This is loops through the long sequence and calls the sorting method for each record. 
https://github.com/questdb/questdb/blob/fbe64151b84ffeeaa4a83cff33b965cbad332338/core/src/main/java/io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java#L115-L127
This is where it sorts the records. The calls to comparator.setLeft and comparator.compare are where the random doubles are generated in this case.
https://github.com/questdb/questdb/blob/fbe64151b84ffeeaa4a83cff33b965cbad332338/core/src/main/java/io/questdb/griffin/engine/orderby/LongTreeChain.java#L75-L117
Given how things are set up I could not think of a way to solve this, but hopefully these insights can help someone else.
