### ISSUE TITLE
Inconsistent Env Var Config Behavior

### ISSUE THREAD

**Issue by sklarsa** [questdb/questdb#2564]
### Describe the bug

https://github.com/questdb/questdb-kubernetes/issues/80

It appears that setting `QDB_` environment variables _doesn't_ always work as expected.  Sometimes, they are ignored.

### To reproduce

Per @mariusgheorghies's investigation earlier today...

```bash
docker run -it questdb/questdb:6.5.3 bash
export QDB_LOG_W_STDOUT_LEVEL=ERROR
export QUESTDB_DATA_DIR=/var/lib/questdb/
/app/bin/java -XX:ErrorFile=${QUESTDB_DATA_DIR}/db/hs_err_pid+%p.log -Dout=conf/log.conf -m io.questdb/io.questdb.ServerMain -d ${QUESTDB_DATA_DIR} -f
```
at this point env is ignored

 After editing /var/lib/questdb/conf/log.conf and seting w.stdout.level to ERROR, it works as expected:
```bash
/app/bin/java -XX:ErrorFile=${QUESTDB_DATA_DIR}/db/hs_err_pid+%p.log -Dout=conf/log.conf -m io.questdb/io.questdb.ServerMain -d ${QUESTDB_DATA_DIR} -f
```

### Expected Behavior

`QDB_` env vars should always take precedence over values in the config file

### Environment

```markdown
- **QuestDB version**: 6.5.3
- **OS**: Docker
- **Browser**:
```

**Comment by joanneong** [comment]
I can reproduce this issue. This only happens if:
1. there is a config property defined (i.e. `-Dout=xxx`) AND
2. this is the first time the server is started

Subsequent reruns work fine.

The reason is as per this comment in the `Dockerfile`:
``` 
# 'conf/log.conf' is a placeholder, it does not exist out of box
# which make logger use default configuration. However, when user configures
# a volume with something like:
#
# docker run -v "$(pwd):/var/lib/questdb/"  questdb/questdb
#
# then one can create 'log.conf' in the 'conf' dir and override logger fully
```

So, before the server is started for the first time, `conf/` and `conf/log.conf` does not exist. As a result, we end up falling back to the default log writer in `LogFactory#configureFromSystemProperties`. This default log writer **does not** take into account any system properties defined:
```
try (InputStream is = LogFactory.class.getResourceAsStream(conf)) {
if (is != null) {
    Properties properties = new Properties();
    properties.load(is);
    logFactory.configureFromProperties(properties, logDir);
    System.err.println("Log configuration loaded from default internal file.");
} else {
    File f = new File(conf);
    if (f.canRead()) {
        try (FileInputStream fis = new FileInputStream(f)) {
            Properties properties = new Properties();
            properties.load(fis);
            logFactory.configureFromProperties(properties, logDir);
            System.err.printf("Log configuration loaded from: %s%n", conf);
        }
    } else {
        logFactory.configureDefaultWriter(); <--- WE FALLBACK HERE AS CONF FILE DOES NOT EXIST YET!
        System.err.println("Log configuration loaded loaded using factory defaults.");
    }
}
```

Looks like `conf/log.conf` is then generated during the first run so subsequent runs work fine. 

I guess we can  follow the suggestion in the Dockerfile and create `conf/log.conf` manually first. But is there any reason why we don't copy this `.conf` file into the Docker image in the first place? That would probably be easier...

**Comment by joanneong** [comment]
Yeah I agree with you @sklarsa , we might want to add logic to pick up environment properties regardless whether the log conf file is present. One way might be to start with some default config, then override with properties in conf file (if present) and finally override with env properties (if present).

For the oddity you mentioned, it is probably helpful to add some logs whenever a property override is processed. The behaviour looks right to me, so don't think there's any functional bug there

**Comment by sklarsa** [comment]
The above PR only addresses the env var emitting issue, still need some time to work on the other aspects of the PR

**Comment by sklarsa** [comment]
Updated the PR to read-and-apply env vars even if a config file is not present

**Comment by sklarsa** [comment]
closed by https://github.com/questdb/questdb/pull/2737
