### ISSUE TITLE
Duplicate Column when using CAST and * in the same SELECT

### ISSUE THREAD

**Issue by javier** [questdb/questdb#2870]
### Describe the bug

When doing `SELECT CAST(anycolumn AS type) AS newName, * FROM table` we get a duplicate column error

If we change the order of arguments and do instead `SELECT *, CAST(anycolumn AS type) AS newName FROM table`, this works

It should always work without errors 

### To reproduce

Go to the demo site at https://demo.questdb.io

This works
`select *, cast(timestamp AS long) AS t from trades
`
This breaks
`select cast(timestamp AS long) AS t , * from trades
`
Same with other datatypes. Example
`select cast(price AS long) AS t , * from trades`

### Expected Behavior

Returns should be returned with no errors. Business as usual

### Environment

```markdown
- **QuestDB version**:6.1.1
- **OS**: demo machine and also locally on Mac M1
- **Browser**: Chrome
```

**Comment by PratyushKumar-0903** [comment]
It looks like the issue is with the order in which the columns are being selected. In the first query, the ***** is being used to select all columns after **cast(timestamp AS long) AS t**. This results in a duplicate column error because **timestamp** is already being selected and given the alias **t**.

To fix this issue, you can either remove the ***** and explicitly list out the columns you want to select, or you can move the ***** to the end of the column list, after any specific columns or column expressions. This will ensure that all columns are selected, but the duplicate column error will not be triggered because the specific columns will be selected first and given their respective aliases.

Here are the two fixed queries:
-- Option 1: Explicitly list out the columns
SELECT cast(timestamp AS long) AS t, col1, col2, ... FROM trades

-- Option 2: Move the * to the end of the column list
SELECT cast(timestamp AS long) AS t , col1, col2, ..., * FROM trades

**Comment by javier** [comment]
Thanks @PratyushKumar-0903. As I explained on the issue description, I know the workaround to make this work, but I believe it is still a bug and the database should work. If it is legal to alias a column and not being marked as a duplicate, column order should not affect the results

**Comment by ryanhamilton** [comment]
I hit the same issue.
