### ISSUE TITLE
web console formatting

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#2906]
### Describe the bug

this query:

```sql
select sin(0.0), sin(-0.0), cos(0.0), cos(-0.0), tan(0.0), tan(-0.0)
```

should return a view with these content:

| sin | sin1  | cos | cos1 | tan | tan1 |
|----|-----|-----|------|----|------|
| 0.0 | -0.0 | 1.0  | 1.0.   | 0.0 | -0.0 |

however it does not.

```
curl -G --data-urlencode \
    "query=select sin(0.0), sin(-0.0), cos(0.0), cos(-0.0), tan(0.0), tan(-0.0)" \
    http://localhost:9000/exp
"sin","sin1","cos","cos1","tan","tan1"
0.0,-0.0,1.0,1.0,0.0,-0.0
```

however the web console removes the signs.

**Comment by amyshwang** [comment]
Note that `NaN` as argument returns `null`.
SELECT acos(2); (absolute value >1, expect `NaN`) returns `null`.

**Comment by ideoma** [comment]
I don't think it is an issue.

There are equivalent ways to write numbers, for example 0.0 is same as -0.0 and it is same as 0E01. All of them are valid and equal.

![image](https://user-images.githubusercontent.com/2159629/212180696-27902273-d424-4266-963a-ac39e7ff6044.png)

As you can see even -0.0 >= 0 returns true

**Comment by ideoma** [comment]
Because of storage design we store NULL values as a special value, not as a bitmap per each row and for DOUBLE type NaN is this special value, QuestDB cannot distinguish between NaN and NULL.

It is not only web console, it will be across all the connection types, PgWire, csv etc. Everywhere NaN will be NULL.

You can try it by querying

```
SELECT NaN

SELECT 1.0 / 0.0
```

the result will be NULLs.

The only option at the moment is to document the limitation.
