### ISSUE TITLE
Duplicate Data Issue when Loading More Data into Buffer

### ISSUE THREAD

**Issue by sid2631** [questdb/questdb#3205]
### Describe the bug

 i am using the nodejs-questdb-client library to collect data from multiple devices and store it in QuestDB. The data is analyzed and only unique rows should be stored. However, I have noticed that sometimes duplicate rows are being inserted into QuestDB, resulting in unexpected behavior.

### To reproduce

Collect data from multiple devices using the nodejs-questdb-client library.
Analyze the data to determine if it needs to be stored or not.
Add the data to a buffer using the Buffer.from() method before sending it to QuestDB for insertion.
Repeat the above steps for a certain duration of time, loading more data into the buffer periodically.
Actual Result:
Duplicate rows of data are being inserted into QuestDB intermittently, resulting in unexpected duplicate data in the database

### Expected Behavior

Only unique rows of data should be inserted into QuestDB, and there should be no duplicates.

### Environment

```markdown
Operating System: macos
Node.js version: 18.16.0
QuestDB version: 6.7
```

**Comment by kuspia** [comment]
1. The logic for determining unique rows of data might not be working correctly. Make sure that your analysis of the data is accurate and that you are correctly identifying and removing duplicates before inserting the data into QuestDB.

2. The data might be arriving out of order or with different timestamps. If the data is arriving at different times or out of order, it might be possible that some data is getting inserted twice. Make sure that the data is being properly ordered and timestamped before being inserted into QuestDB.

3. The buffer size might be too large. If the buffer is too large, it is possible that some data is being inserted twice due to a race condition. Try reducing the buffer size and see if the duplicate data issue persists.

4. There might be a bug in the nodejs-questdb-client library or in QuestDB itself. Check the library's documentation and issues to see if there are any known issues related to duplicate data. Additionally, check the QuestDB documentation or contact their support team to see if they are aware of any similar issues.

To troubleshoot this issue further, you can try logging and inspecting the data before and after it is inserted into QuestDB. This can help you identify any patterns or issues with the data that might be causing the duplicates. You can also try reproducing the issue with a smaller subset of data to help isolate the problem.
