### ISSUE TITLE
TimedOut

### ISSUE THREAD

**Issue by projectandresearch** [questdb/questdb#3219]
### Describe the bug

I am unable to perform any query using Rust sqlx v0.6.2 when connecting to a QuestDB database. On the client's side, I get the error "PoolTimedOut," but there is no explicit error in QuestDB's log.

### To reproduce

use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150")
        .execute(&pool)
        .await?;

    Ok(())
}

### Expected Behavior

Retrieve the row(s) from the table that have an integer column with a value of 150

### Environment

```markdown
- **QuestDB version**: 7.1.1 .
- **sqlx**: 0.6.2.
- **OS**: macOS 13.2.1 .
```

**Comment by Abir-0007** [comment]
<html>
<body>
<header id="package" style="padding: 1em 0px 0px; background: rgb(53, 55, 70); color: rgb(188, 194, 215); font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, &quot;trebuchet ms&quot;, roboto, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="inner-col" style="padding: 0px 1em; margin: 0px auto; max-width: 60em; box-sizing: border-box;"><h2 style="font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, ubuntu, roboto, -apple-system, helvetica, sans-serif; overflow-wrap: break-word; hyphens: auto; font-size: 3.5em; line-height: 1.08; margin: 0.44em 0px 0px; color: rgb(204, 209, 225);"><span property="name">sqlx-core</span></h2><p class="desc" style="margin: 0.4em 0px; font-weight: 300; font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, ubuntu, roboto, -apple-system, helvetica, sans-serif;">Core of SQLx, the rust SQL toolkit. Not intended to be used directly.</p><p class="byline" style="cursor: default; margin: 0px; line-height: 1.33;">by<span> </span><a href="https://lib.rs/~mehcode" class="owner" title="owner" property="author" typeof="Person" style="text-decoration: none; padding: 0.4em 0px; color: rgb(73, 164, 228); white-space: nowrap;"><span property="name">Ryan Leckey</span></a>,<span> </span><a href="https://lib.rs/~abonander" class="owner" title="owner" property="author" typeof="Person" style="text-decoration: none; padding: 0.4em 0px; color: rgb(73, 164, 228); white-space: nowrap;"><span property="name">Austin Bonander</span></a>,<span> </span><a href="https://github.com/janaakhterov" class="contributor" title="contributor" property="author" typeof="Person" style="text-decoration: none; padding: 0.4em 0px; color: inherit; white-space: nowrap;"><span property="name">Jana Akhterov</span></a><span> </span><span class="contributors" style="white-space: nowrap;">and<span> </span><a href="https://github.com/launchbadge/sqlx/graphs/contributors" style="text-decoration: none; padding: 0.4em 0px; color: rgb(73, 164, 228); white-space: nowrap;">97 contributors</a></span></p><nav style="user-select: none; margin: 2em 0px 0px;"><ul style="white-space: nowrap; font-size: 0.85em; display: flex; flex-shrink: 1; flex-wrap: wrap-reverse; list-style: none; margin: 0px; padding: 0px;"><li style="cursor: default; margin: 0px 0.5em 0px 0px; padding: 0px 0px 2px;"><a class="button" href="https://lib.rs/install/sqlx-core" style="text-decoration: none; padding: 0.42em 1.9em 0.4em; display: block; color: rgb(73, 164, 228); border-radius: 3px; margin-right: 1em; background-color: rgb(66, 69, 87);">Install</a></li><li style="cursor: default; margin: 0px 0.5em 0px 0px; padding: 0px 0px 2px;"><a href="https://docs.rs/sqlx-core" style="text-decoration: none; padding: 0.42em 1.9em 0.4em; display: block; color: rgb(73, 164, 228);">API reference</a></li><li style="cursor: default; margin: 0px 0.5em 0px 0px; padding: 0px 0px 2px;"><a href="https://github.com/launchbadge/sqlx/tree/ec60b1d32d60844010e5cc4839e4f783c64ae74c/sqlx-core" property="url" style="text-decoration: none; padding: 0.42em 1.9em 0.4em; display: block; color: rgb(73, 164, 228);">GitHub (launchbadge)</a></li></ul></nav></div></header><main style="min-height: 52vh; color: rgb(188, 194, 215); font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, &quot;trebuchet ms&quot;, roboto, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(40, 42, 54); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="inner-col" style="padding: 0px 1em; margin: 0px auto; max-width: 60em; box-sizing: border-box;"><section id="readme-deps" style="display: flex;"><div style="min-width: 75%;"><section class="about-crate" style="display: flex; margin: 0px 0px 2em; flex-wrap: wrap; justify-content: space-between; flex-grow: 1;"><section id="versions" style="margin: 0px; padding: 0px; border-left: 0px; color: var(--text-color);"><h3 style="font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, ubuntu, roboto, -apple-system, &quot;trebuchet ms&quot;, sans-serif; font-size: 1em; margin: 1em 0px 0px;"><a href="https://lib.rs/crates/sqlx-core/versions" style="text-decoration: none; color: rgb(73, 164, 228);">39 releases</a></h3>

0.7.0-alpha.2 | Mar 17, 2023
-- | --
Mar 21, 2023
Sep 14, 2022
Jun 16, 2022
Nov 27, 2019

</section><section id="downloads" style="margin: 0px 0px 0px 1em; padding: 0px 0px 0px 1em;"><p class="top-n" style="margin: 1em 0px 0.5em;">#<b style="font-weight: 500; color: rgb(247, 245, 255);">1709</b><span> </span>in<span> </span><a href="https://lib.rs/database" title="Crates to interface with database management systems." style="text-decoration: none; color: rgb(73, 164, 228);">Database interfaces</a></p><svg viewBox="0 0 182 56" width="182" height="56"><line x1="1" x2="181" y1="5.230769" y2="5.230769" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="9.461538" y2="9.461538" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="13.692307" y2="13.692307" stroke="black" stroke-width="1.5" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="17.923077" y2="17.923077" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="22.153847" y2="22.153847" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="26.384615" y2="26.384615" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="30.615385" y2="30.615385" stroke="black" stroke-width="1.5" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="34.846153" y2="34.846153" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="39.076923" y2="39.076923" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="43.307693" y2="43.307693" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="47.53846" y2="47.53846" stroke="black" stroke-width="1.5" stroke-linecap="butt" stroke-opacity="0.3"></line><line x1="1" x2="181" y1="51.76923" y2="51.76923" stroke="black" stroke-width="0.42105263" stroke-linecap="butt" stroke-opacity="0.3"></line><rect x="0" y="47" width="11" height="10" fill="#93cd91" fill-opacity="0.95"></rect><rect x="11" y="41" width="12" height="16" fill="#8dce88" fill-opacity="0.95"></rect><rect x="23" y="35" width="11" height="22" fill="#87cf7f" fill-opacity="0.95"></rect><rect x="34" y="35" width="12" height="22" fill="#82ce7a" fill-opacity="0.95"></rect><rect x="46" y="34" width="11" height="23" fill="#7cce74" fill-opacity="0.95"></rect><rect x="57" y="31" width="11" height="26" fill="#75cd6d" fill-opacity="0.95"></rect><rect x="68" y="33" width="12" height="24" fill="#70cd69" fill-opacity="0.95"></rect><rect x="80" y="32" width="11" height="25" fill="#6acc63" fill-opacity="0.95"></rect><rect x="91" y="32" width="11" height="25" fill="#64cb5e" fill-opacity="0.95"></rect><rect x="102" y="32" width="12" height="25" fill="#5dcb58" fill-opacity="0.95"></rect><rect x="114" y="31" width="11" height="26" fill="#55ca52" fill-opacity="0.95"></rect><rect x="125" y="29" width="12" height="28" fill="#4cca4a" fill-opacity="0.95"></rect><rect x="137" y="27" width="11" height="30" fill="#42c941" fill-opacity="0.95"></rect><rect x="148" y="29" width="11" height="28" fill="#39c83d" fill-opacity="0.95"></rect><rect x="159" y="31" width="12" height="26" fill="#30c73a" fill-opacity="0.95"></rect><rect x="171" y="32" width="11" height="25" fill="#23c634" fill-opacity="0.95"></rect><rect x="0.5" y="0.5" width="181" height="55" stroke="black" fill="none" stroke-opacity="0.3" stroke-linecap="square" stroke-width="1"></rect></svg><p style="margin: 0px;"><b style="font-weight: 500; color: rgb(247, 245, 255);">375,661</b><span> </span>downloads per month<br>Used in<span> </span><a href="https://lib.rs/crates/sqlx-core/rev" style="text-decoration: none; color: rgb(73, 164, 228);"><b style="font-weight: 500; color: rgb(247, 245, 255);">524</b><span> </span>crates (17 directly)</a></p></section><section id="sloc" style="margin: 0px 0px 0px 1em; padding: 0px 0px 0px 1em; flex: 0 1 8em;"><section id="license" style="margin: 1em 0px 0.5em;"><b property="license" style="font-weight: 500; color: rgb(247, 245, 255);">MIT/Apache</b></section><p style="margin: 0.5em 0px;"><span title="96KB as tarball">395KB</span><br><span title="7,798">8K<span> </span></span><abbr title="Lines of code, excluding comments">SLoC</abbr></p></section></section><section id="lib_intro" class="readme" vocab="" style="overflow: auto;"><p>Core of SQLx, the rust SQL toolkit.</p><h3 id="readme-note-semver-exempt-api" style="font-family: &quot;fira sans ot&quot;, &quot;fira sans&quot;, ubuntu, roboto, -apple-system, &quot;trebuchet ms&quot;, sans-serif;">Note: Semver Exempt API</h3><p>The API of this crate is not meant for general use and does<span> </span><em>not</em><span> </span>follow Semantic Versioning. The only crate that follows Semantic Versioning in the project is the<span> </span><code style="background: rgb(32, 33, 41); font-size: 0.9em; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 3px 5px 2px; border-radius: 3px; color: rgb(242, 243, 247);"><tt class="src-rs" style="font: inherit;">sqlx</tt></code><span> </span>crate itself. If you are building a custom SQLx driver, you should pin an exact version for<span> </span><code style="background: rgb(32, 33, 41); font-size: 0.9em; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 3px 5px 2px; border-radius: 3px; color: rgb(242, 243, 247);"><tt class="txt-plain" style="font: inherit;">sqlx-core</tt></code><span> </span>to avoid breakages:</p><pre lang="toml" style="background: rgb(25, 26, 32); font-size: 0.9em; overflow: auto; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 0.5em 2ex; border-radius: 3px; line-height: 1.45; white-space: pre-wrap; color: rgb(255, 255, 255);"><code style="background: 0px 0px; font-size: inherit; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 0px; border-radius: 0px; color: rgb(242, 243, 247);"><tt class="src-toml" style="font: inherit;">sqlx-core = { version = "=0.6.2" }
</tt></code></pre><p>And then make releases in lockstep with<span> </span><code style="background: rgb(32, 33, 41); font-size: 0.9em; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 3px 5px 2px; border-radius: 3px; color: rgb(242, 243, 247);"><tt class="txt-plain" style="font: inherit;">sqlx-core</tt></code>. We recommend all driver crates, in-tree or otherwise, use the same version numbers as<span> </span><code style="background: rgb(32, 33, 41); font-size: 0.9em; font-family: sfmono-regular, consolas, &quot;liberation mono&quot;, menlo, monospace, monospace; padding: 3px 5px 2px; border-radius: 3px; color: rgb(242, 243, 247);"><tt class="txt-plain" style="font: inherit;">sqlx-core</tt></code><span> </span>to avoid confusion.</p></section></div></section></div></main>
</body>
</html>sqlx-core
Core of SQLx, the rust SQL toolkit. Not intended to be used directly.

by [Ryan Leckey](https://lib.rs/~mehcode), [Austin Bonander](https://lib.rs/~abonander), [Jana Akhterov](https://github.com/janaakhterov) and [97 contributors](https://github.com/launchbadge/sqlx/graphs/contributors)

[39 releases](https://lib.rs/crates/sqlx-core/versions)
0.7.0-alpha.2	Mar 17, 2023
0.6.3	Mar 21, 2023
0.6.2	Sep 14, 2022
0.6.0	Jun 16, 2022
0.0.0	Nov 27, 2019
#1709 in [Database interfaces](https://lib.rs/database)

375,661 downloads per month
Used in [524 crates (17 directly)](https://lib.rs/crates/sqlx-core/rev)

MIT/Apache
395KB
8K SLoC

Core of SQLx, the rust SQL toolkit.

Note: Semver Exempt API
The API of this crate is not meant for general use and does not follow Semantic Versioning. The only crate that follows Semantic Versioning in the project is the sqlx crate itself. If you are building a custom SQLx driver, you should pin an exact version for sqlx-core to avoid breakages:

sqlx-core = { version = "=0.6.2" }
And then make releases in lockstep with sqlx-core. We recommend all driver crates, in-tree or otherwise, use the same version numbers as sqlx-core to avoid confusion.

**Comment by bziobrowski** [comment]
Please refrain from posting bad copies of existing issues (  https://github.com/questdb/questdb/issues/3204  int his case ).
