### ISSUE TITLE
Numerical Artefact when using `round` 

### ISSUE THREAD

**Issue by rueschm** [questdb/questdb#3462]
### Describe the bug

The following query `select round(cast((1.0/0.0) as double))` results in 9223372036854776000 

I would expect `null` as a result

### To reproduce

reproducible on the demo instance with the above query.

### Environment

```markdown
- **QuestDB version**:
7.1.3
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
Web console shows Infinity values as null but if you run `select cast((1.0/0.0) as double) ` (or just `select 1.0/0.0`)  via pg wire , you'll get `Infinity` . 
`round(Infinity)` should return `Infinity`, not null .  

The actual issue is that inside round calculations cast value to long at one point and thus limit the range to what long can hold .

**Comment by marregui** [comment]
let's call this a feature, and thus close the issue. Thank you for the report!!!!!
