### ISSUE TITLE
Insert data failed when millions of lines in table

### ISSUE THREAD

**Issue by wanyuetian** [questdb/questdb#3870]
### Describe the bug

I hava 4 million rows in "RcvMsg_e293455f-8330-4f9a-af7d-cb9e81a7808f" table 
![image](https://github.com/questdb/questdb/assets/16832207/39f2a1a7-a4d9-440b-9970-b84d13043f56)

But when I insert a row to this table,it remind me insert successfully.
![image](https://github.com/questdb/questdb/assets/16832207/2b4e947b-c354-4ab7-9cd1-cdcc2787160b)

After that, when I query this inserted row, I can't get this row.
![image](https://github.com/questdb/questdb/assets/16832207/313aeb3c-b686-4c08-9e54-eb97ef2d4efa)

Here is my sqls

1) insert into "RcvMsg_e293455f-8330-4f9a-af7d-cb9e81a7808f" VALUES('1111111111', 1, now(),123,now(), 0, 2, 0, 0, 8, 0, '1234567890123456')

2) select * from "RcvMsg_e293455f-8330-4f9a-af7d-cb9e81a7808f" where Msg_Data='1234567890123456';

### Environment

```markdown
- **QuestDB version**:7.3.2
- **OS**:Ubuntu 22.04
- **Browser**: Google Chrome 118.0.5993.70 on Macos Intel CPU
```

**Comment by ideoma** [comment]
Because it's a WAL table inserts are asynchronous and there is a delay between insert is reported as successful and the data is queriable in the table.

If the data is still not in the table after a significant delay (depends on the system load) it can happen that WAL application failed on this transaction or before it. You can query the status of the WAL tables using SQL

```SQL
select * from wal_tables()
```

If the table is set as suspended, you can find the error in the log. You can grep for "ApplyWal2TableJob" to find it quicker.

**Comment by wanyuetian** [comment]
thanks for repsone. 
it's really in suspend status.
![image](https://github.com/questdb/questdb/assets/16832207/b30cf613-f1cc-4c9b-8f94-bcab60a0b773)

But check the log output, I can't find the error msg.
<img width="1715" alt="image" src="https://github.com/questdb/questdb/assets/16832207/fec34862-38d0-4612-b29f-92dace9d02c4">

**Comment by ideoma** [comment]
There was a bug fixe released in 7.3.3 which can help, try to update

**Comment by wanyuetian** [comment]
@ideoma Thanks for your help. I will try it later.

**Comment by wanyuetian** [comment]
It works. Thank you very much.
