### ISSUE TITLE
IODispatcherTest failed tests and Error:Hash of jdk.unsupported 

### ISSUE THREAD

**Issue by CatspersCoffee** [questdb/questdb#457]
**Describe the bug(s):**

After running mvn clean and mvn package i get the error (using release 5.0.1):

```
Error: Hash of jdk.unsupported (1fd4ffb477c0fb59022daeab3a0bf32a4681e8f8d540396f3641503915fd54ca) differs to expected hash (2f3dae909f60914354efbc2acbff4a6c976ac1fb47851afa737262816b828381) recorded in java.base
[[1;31mERROR[m] Command execution failed.
```

On another machine in docker, we get the following error:

```
Failed tests: 
  IODispatcherTest.testJsonQueryBadUtf8:1899->testJsonQuery:4986->testJsonQuery:4966->testJsonQuery0:4993->lambda$testJsonQuery0$38:5079->lambda$testJsonQuery$37:4974->sendAndReceive:4862->sendAndReceive:4895->sendAndReceive:4946 Error at: 208, local=10
  IODispatcherTest.testJsonQueryLimitColumnsUtf8:2398->testJsonQuery:4986->testJsonQuery:4966->testJsonQuery0:4993->lambda$testJsonQuery0$38:5079->lambda$testJsonQuery$37:4974->sendAndReceive:4862->sendAndReceive:4895->sendAndReceive:4946 Error at: 213, local=24
  IODispatcherTest.testJsonUtf8EncodedColumnName:3250->testJsonQuery:4966->testJsonQuery0:4993->lambda$testJsonQuery0$38:5079->lambda$testJsonQuery$37:4974->sendAndReceive:4862->sendAndReceive:4895->sendAndReceive:4946 Error at: 208, local=19
  IODispatcherTest.testJsonUtf8EncodedQuery:3279->testJsonQuery:4986->testJsonQuery:4966->testJsonQuery0:4993->lambda$testJsonQuery0$38:5079->lambda$testJsonQuery$37:4974->sendAndReceive:4862->sendAndReceive:4895->sendAndReceive:4946 Error at: 220, local=31

Tests run: 4192, Failures: 4, Errors: 0, Skipped: 6
```

**complete log file for first error:**
https://gist.github.com/CatspersCoffee/4bc593bbc9326ccb70074b73184f994c

**complete log file for second set of test errors:**
https://gist.github.com/mortenpi/65741ee47038b0b698d6df8159449118

**To Reproduce**
installed and cloned as per the instructions: https://github.com/questdb/questdb
Tested using master branch and also release 5.0.1 both produce the same errors respectively. 

**Environment**
please see links above, complete environment details provided.

**Comment by bluestreak01** [comment]
Can you try to run test with the following JVM arg:

```
--add-exports java.base/jdk.internal.math=io.questdb
```

**Comment by CatspersCoffee** [comment]
> Can you try to run test with the following JVM arg:
> 
> ```
> --add-exports java.base/jdk.internal.math=io.questdb
> ```

Hi, thank you for the reply. Unfortunately we have minimal experience with java development and maven, could you please tell us exactly how to pass this argument into the compiler? thank you

**Comment by mortenpi** [comment]
We've done some more debugging now. It looks like we're running into multiple independent build/test issues.

* If we run the tests (i.e. remove `-DskipTests`), we get these `IODispatcherTest` failures. We haven't tested the `--add-exports java.base/jdk.internal.math=io.questdb` suggestion, since we're unsure how to pass that correctly through Maven.

* Without the tests, the build still reports a failure (due to a hash not matching). But the `.jar` file does actually get built and appears to work correctly.

  The hash problem may actually be a problem in the openjdk of Ubuntu (20.04) / Debian: [Launchpad issue](https://bugs.launchpad.net/ubuntu/+source/openjdk-14/+bug/1868699) and related [Debian issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944738). This should be easy to reproduce with e.g. a vanilla Ubuntu Docker image, but I am not sure if there is anything actionable to do here.

* The latest _master_ seems to fail to populate the database directory though. This is what we get if we start QuestDB with an empty `$HOME/foo`:

  ```
  # java -p core/target/core-5.0.2-SNAPSHOT.jar -m io.questdb/io.questdb.ServerMain -d $HOME/foo
  QuestDB server 5.0.2-SNAPSHOT
  Copyright (C) 2014-2020, all rights reserved.

  2020-06-30T03:28:18.656832Z I server-main extracted [path=/root/foo/public/573e9313e05d89f4acb5d005476c61bb.woff]
  2020-06-30T03:28:21.542708Z I server-main extracted [path=/root/foo/public/6437d5f4c14e01aaf4801aef3909151b.woff]
  2020-06-30T03:28:21.543220Z I server-main extracted [path=/root/foo/public/7dafb1a4bab4938a38b2d68d9c4575a9.woff]
  2020-06-30T03:28:21.544560Z I server-main extracted [path=/root/foo/public/a940d584750708f5435ce2c523498ddb.woff]
  2020-06-30T03:28:21.545115Z I server-main extracted [path=/root/foo/public/d0b483ce9717b92b4bf815d5d4db597a.woff]
  2020-06-30T03:28:21.545340Z I server-main extracted [path=/root/foo/public/index.html]
  2020-06-30T03:28:21.546921Z I server-main extracted [path=/root/foo/public/qdb.css]
  2020-06-30T03:28:21.557896Z I server-main extracted [path=/root/foo/public/qdb.js]
  2020-06-30T03:28:21.558167Z I server-main extracted [path=/root/foo/public/assets/console-configuration.json]
  2020-06-30T03:28:21.558384Z I server-main extracted [path=/root/foo/public/assets/favicon.png]
  2020-06-30T03:28:21.562531Z I server-main extracted [path=/root/foo/conf/mime.types]
  Exception in thread "main" java.io.FileNotFoundException: /root/foo/conf/server.conf (No such file or directory)
  	at java.base/java.io.FileInputStream.open0(Native Method)
  	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
  	at io.questdb@5.0.2-SNAPSHOT/io.questdb.ServerMain.main(ServerMain.java:98)
  ```

  The released 5.0.1 tag starts up nicely though, so it looks like this was introduced after 5.0.1 was tagged.

  Note: this is running in a Docker container, which is why everything is `root`.

**Comment by mpsq** [comment]
@mortenpi thanks for the extra details. I tried both `mvn clean package` and `mvn clean package -DskipTests` on Ubuntu 20.04 (via Docker) and I was able to reproduce the issues. We will look into it!

**Comment by bluestreak01** [comment]
to troubleshoot for the Dispatcher tests, could you let us know output of `locale` command?

**Comment by mpsq** [comment]
@mortenpi I have some news on your issues:

1. This is an issue with OpenJDK 11 bundled by Canonical on Ubuntu 20.04. Canonical add a few patches on top of the vanilla JDK and something is broken there. There is nothing we can do on our side, Canonical has to fix this issue. In the meantime you can use the vanilla OpenJDK from the AdoptOpenJDK project:

```
apt-get update
apt-get install software-properties-common wget
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
apt-get install adoptopenjdk-11-hotspot
```

More on this here 

2. This is a locale issue, by default on Ubuntu 20.04 for Docker, the locale is set to `POSIX` you can verify this by running `locale`. We will work to make the tests pass even when the locale is set to `POSIX`, in the meantime you can set the locale to `en_US.UTF-8`:

```
apt-get update
apt-get install locales
echo "LANG=en_US.UTF-8" > /etc/default/locale
locale-gen
export LANG=en_US.UTF-8
```

And the tests will pass :)

**Comment by bluestreak01** [comment]
The tests fail because we hardcode malformed UTF8 characters in .java file, for example:

```java
                "GET /query?query=�������&limit=10 HTTP/1.1\r\n" +
                        "Host: localhost:9001\r\n" +
                        "Connection: keep-alive\r\n" +
                        "Cache-Control: max-age=0\r\n" +
                        "Upgrade-Insecure-Requests: 1\r\n" +
                        "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36\r\n" +
                        "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\n" +
                        "Accept-Encoding: gzip, deflate, br\r\n" +
                        "Accept-Language: en-GB,en-US;q=0.9,en;q=0.8\r\n" +
                        "\r\n",
                "HTTP/1.1 400 Bad request\r\n" +
                        "Server: questDB/1.0\r\n" +
                        "Date: Thu, 1 Jan 1970 00:00:00 GMT\r\n" +
                        "Transfer-Encoding: chunked\r\n" +
                        "Content-Type: application/json; charset=utf-8\r\n" +
                        "Keep-Alive: timeout=5, max=10000\r\n" +
                        "\r\n" +
                        "58\r\n" +
                        "{\"query\":\"�������\",\"error\":\"Bad UTF8 encoding in query text\",\"position\":0}\r\n" +
                        "00\r\n" +
                        "\r\n"

```

when questdb _compiled_ with system encoding other than UTF8, javac - the compiler effectively reinterprets characters from .java file differently thus making server respond differently. Why request and response do not match when they both in the same source file? "chunked" encoding is the answer - the length (58) changes too.

This isn't a problem with server or encoding implementation, but rather with test. One way to fix it is to send base-64 request and assert base-64 response. But that's some effort considering we have other more important things to implement.

**Comment by mpsq** [comment]
The tests are now passing on master even when locale is set to `POSIX`.
