### ISSUE TITLE
support noop group by clause

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#464]
This SQL errors out unnecessarily:

```sql
select x, sum(y) from tab group by x
```

`group by x` must be consumed and validated to allow friction free user experience

**Comment by lbowman** [comment]
@bluestreak01 Is this an intentional change from the docs: http://questdb.io/docs/sqlExtensions#important-differences-from-standard-sql

"We do not support explicit GROUP BY clause."

Is the idea then to validate that the provided group by clause matches the implied grouping and then effectively ignore it?

**Comment by TheTanc** [comment]
Yes this is intentional. We noticed a lot of users were unaware of the implicit grouping. So they tried GROUP BY clauses and got error messages. 

As a first step, it could validate the columns and let the implicit group by perform in the background. This would remove 99.99% of the friction and make it easier to migrate existing queries to QuestDB.

**Comment by den-crane** [comment]
about migration, Mysql does the opposite. It applies any() if a column not mentioned in group by

```
select a, sum(b) from (select 1 a, 1 b union all select 333, 1) x;
+------+--------+
| a    | sum(b) |
+------+--------+
|    1 |      2 |
+------+--------+

```

**Comment by bluestreak01** [comment]
we do the same, that said it looks like SQL in MySQL has mulfunctioned? There should be two keys in the output, as below? 

![image](https://user-images.githubusercontent.com/7276403/88084847-e5341380-cb7c-11ea-8264-ebdce5f3ddbc.png)

**Comment by den-crane** [comment]
by default / with disabled strictness

if one execute  `select a, sum(b)` (without group by section) mysql does `select any(a), sum(b)  group by 1 `
