### ISSUE TITLE
Add a volume-weighted moving average function (VWMA)

### ISSUE THREAD

**Issue by nwoolmer** [questdb/questdb#4727]
### Is your feature request related to a problem?

Related to: https://github.com/questdb/questdb/issues/4620

We should support VWMA in QuestDB for finance use-cases.

VWAP: `sum(price * quantity) / sum(quantity)`
VWMA is similar, but with a moving average window.

For a 3 trade window:

`((price1 * quantity1) + (price2 * quantity2) + (price3 * quantity3)) / (quantity1 + quantity2 + quantity3)`

### Describe the solution you'd like.

Support for volume weighted moving average

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

**Comment by siddharth0815** [comment]
https://questdb.io/docs/reference/function/window/#avg
@nwoolmer I went through this document, and I guess VWMA will be implemented with the **PARTITION BY** clause in the same way, that's how the window will be defined for quantity and price.
Correct me if I am wrong here.

**Comment by siddharthagZeta** [comment]
@puzpuzpuz @nwoolmer 
Action items till now :
- Create a VolumeWeightedMovingAverageFunctionFactory class which implements FunctionFactory and returns isWindow()= true which accepts 2 sigArgs - vwma(DD)
- Added it in module info so that it can be loaded in factory list and get identified by token (vwma)
- change paramCount condition for window functions in SqlCodeGenerator.generateSelectWindow() 
to ast.paramCount > 2

Now I'm analysing what happens in
- factory instance creation 
- how windowCursor fetches average
Please tell if this is the correct way to approach the problem or is anything I'm missing here, also if you me to explore something in addition to the ones mentioned above , please mention

**Comment by siddharth0815** [comment]
@puzpuzpuz @nwoolmer
Action items till now :
 - Create a `VolumeWeightedMovingAverageFunctionFactory` class which implements `FunctionFactory` and returns `isWindow()= true` which accepts 2 sigArgs - `vwma(DD)`
 - Added it in `module-info.java` so that it can be loaded in factory list and get identified by token **vwma**
 - Change paramCount condition for window functions in `SqlCodeGenerator.generateSelectWindow()`
to `ast.paramCount > 2`

Now I'm analysing what happens in : 
 - Factory instance creation
 - How windowCursor fetches average
 
Please tell if this is the correct way to approach the problem or is anything I'm missing here, also if you want me to explore something in addition to the ones mentioned above, please mention.

**Comment by puzpuzpuz** [comment]
You may use `AvgDoubleWindowFunctionFactory` as the starting point. It's worth running `WindowFunctionTest` with debugger and going through the calls to understand better when it's initialized and how it works.

@nwoolmer if you can add more hints here, please go ahead.

**Comment by bzhu23** [comment]
Hello, I'm interested on working on this! Added a pull request recently with some of the above comments in mind, it is a bit dense (trying to add support for both partition-by and order-by clauses) but order-by seems to work. Unit tests and partition-by support is still WIP but wanted to see if the work is in the right direction :) The PR is here: https://github.com/questdb/questdb/pull/4749

**Comment by siddharth0815** [comment]
@nwoolmer I can contribute in the same PR. :)

**Comment by siddharth0815** [comment]
Hi @nwoolmer I went through the logic of the `(avg)` window function 
Please validate my understanding here, post that I'll proceed with coding

Now basically we have 2 types of queries here :
1.  Computation on values (of some columns) contained in rows between given offsets `ROW OVER PARTITION`
2.  Computation on values (of some columns) in rows containing values between given range `RANGE OVER PARTITION`

**Most complicated case**
The window is bounded from the lower end by a given `offset/timestamp-diff` and the higher end by some `offset/timestamp-diff/current row`.

**Case Handling**
In such cases, 
We use 2 data structures : 
1. **Map**: keeps track of values which will change in each iteration basis partition key (sum/avg/ring buffer offset) etc
2. **Ring buffer**: To keep track of old values which may/may not be considered in current computation

1. A `Ring buffer` type data structure is used where memory locations are allocated by default for each partition key 
2. Starting offsets of those memory locations are mapped to the partition key in `Map` for further reference
3.  Computable values of the records are put circularly,  it is discarded (if out of range) and replaced as new index is calculated by modulo with `bufferCapacity`

Questions

1. Wanted to know in brief about how memory allocation works for the ring buffer (There's a case where we add more memory if buffer reaches capacity)?
2. How is the calculated _average/sum_ at each record iteration returned to the result (as `computeNext()` is a `void` function)?
