### ISSUE TITLE
Data not available immediately after Insert. Is there any way to ensure it is available immediately after insert?

### ISSUE THREAD

**Issue by RajvanshR** [questdb/questdb#4887]
### To reproduce

Below is the code snippet. I am trying to read the data immediately after Insert. I also tried using the config cairo.commit.mode=sync but result is same (only runtime increased).

```
        for (int i = 1; i <= 100; i++ ) {

            try (Sender sender = Sender.fromConfig("http::addr=localhost:9010;")) {

                sender.table("testtable")
                        .symbol("column1", String.valueOf(i))
                        .stringColumn("column2",
                                String.valueOf(i))
                        .doubleColumn("column3", i)
                        .timestampColumn("time", Instant.now())
                        .at(Instant.now());
                sender.flush();
                log.info("Insert count: {}", i);
            }

            try (PreparedStatement preparedStatement = connection.prepareStatement(
                    "SELECT count(*) from testtable;")) {
                try (ResultSet rs = preparedStatement.executeQuery()) {
                    while (rs.next()) {
                        log.info("Row count: {}", rs.getLong(1));
                    }
                }
            }
        }
```

```
2024-08-21T19:12:09.530+01:00  INFO 201309 ---  : Insert count: 1
2024-08-21T19:12:09.548+01:00  INFO 201309 ---  : Row count: 0
2024-08-21T19:12:09.552+01:00  INFO 201309 ---  : Insert count: 2
2024-08-21T19:12:09.553+01:00  INFO 201309 ---  : Row count: 1
2024-08-21T19:12:09.556+01:00  INFO 201309 ---  : Insert count: 3
2024-08-21T19:12:09.557+01:00  INFO 201309 ---  : Row count: 3
```

### QuestDB version:

8.0.0

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04.2 LTS

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Rajvansh 

### Affiliation:

N/A

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by glasstiger** [comment]
This is expected, data is ingested into WAL first, then moved into the table.
WAL architecture details:
https://questdb.io/docs/concept/write-ahead-log/

Basically `sender.flush()` forces commits, which creates a new transaction after each row in the WAL.
These transactions then moved into the actual table by a job _asynchronously_.
Only after that the data is available for read.
The latency caused by the background job is negligible in general, and it does not cause any problem.

However, if this is really an issue, you can choose to create a non-WAL table instead.
https://questdb.io/docs/concept/write-ahead-log/#wal-configurations
Or just convert the existing table to non-WAL:
https://questdb.io/docs/reference/sql/alter-table-set-type/

Data is immediately available for read from a non-WAL table, because the transactions are written synchronously into the table, but non-WAL tables have many drawbacks:
 - performance is worse
 - writing data via multiple interfaces can result in `table busy` errors because each interface tries to own the table for writing
 - replication is not supported (enterprise only)
 - non-WAL tables are considered legacy, at some point support might discontinue

**Comment by RajvanshR** [comment]
Thanks for the detailed information. I think this is what I need. I cannot seem to make the insert work on a non WAL table. I get the error io.questdb.cairo.CairoException: [0] cannot lock table name registry file [path=/root/.questdb/db]
The table testtable is in path  /root/.questdb/db


```
        final CairoConfiguration configuration = new DefaultCairoConfiguration("/root/.questdb/db");

            try (CairoEngine engine = new CairoEngine(configuration)) {
                final SqlExecutionContext ctx = new SqlExecutionContextImpl(engine, 1)
                        .with(AllowAllSecurityContext.INSTANCE, null);
                engine.ddl("CREATE TABLE IF NOT EXISTS testtable1 (" +
                        "a int, b byte, c short, d long, e float, g double, h date, " +
                        "i symbol, j string, k boolean, l geohash(8c), ts timestamp" +
                        ") TIMESTAMP(ts) PARTITION BY DAY BYPASS WAL", ctx);

                // write data into WAL
                final TableToken tableToken = engine.getTableTokenIfExists("testtable1");
                try (TableWriter writer = engine.getWriter(tableToken, "test")) {
//                    for (int i = 0; i < 3; i++) {
                        TableWriter.Row row = writer.newRow(Os.currentTimeMicros());
                        row.putInt(0, 123);
                        row.putByte(1, (byte) 1111);
                        row.putShort(2, (short) 222);
                        row.putLong(3, 333);
                        row.putFloat(4, 4.44f);
                        row.putDouble(5, 5.55);
                        row.putDate(6, System.currentTimeMillis());
                        row.putSym(7, "xyz");
                        row.putStr(8, "abc");
                        row.putBool(9, true);
                        row.putGeoHash(10, GeoHashes.fromString("u33dr01d", 0, 8));
                        row.append();
//                    }
                    writer.commit();
                }
            }
```

**Comment by glasstiger** [comment]
The above code is for embedded mode when QuestDB does not run as a separate process, instead you need to manage the entire database in-process.

You should be able to user the client (Sender) to ingest data, but with TCP protocol.
HTTP is not supported for non-WAL tables.
This goes back to my previous point that non-WAL tables are considered legacy, and should be avoided if possible.

What is your use case?
Why is it important for you to know when the data is applied to the table for read?
Does inserting and reading the data really have to be synchronized?

**Comment by RajvanshR** [comment]
Thanks @glasstiger for taking time for this. My design may be wrong and happy to change if there is a possibility with WAL.

I have simplified the use case as below.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Rajvansh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Rajvansh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Time   Stamp | Record Status | Comments
-- | -- | --
2024-08-21T19:12:09.530+01:00 | TO_BE_PROCESSED | > Reader picks this record   sends for processing.      > Writer to add a new row with columns modified with new Status.
2024-08-21T19:12:09.531+01:00 | SENT_FOR_PROCESSING | > Writer puts a new line with   modified columns and latest status.
2024-08-21T19:12:09.532+01:00 |   | > As this is WAL, there is a   chance that reader trying to pick the latest record gets the record at   "2024-08-21T19:12:09.530+01:00 " with status   "TO_BE_PROCESSED" and will try to process again



</body>

</html>

**Comment by glasstiger** [comment]
hi @RajvanshR, sorry for the late reply. I was OOO, but back now.
I have been thinking and if your Reader and Writer are not synchronized somehow, I have a feeling that you would have issues regardless of WAL.
A possible solution could use Reader and Writer processes/threads which keep track of what have been processed, and select only the new rows from the table.

I assume there is a Producer too which creates the records in the first place.
The Producer would keep inserting the data like:
```
INSERT INTO table(timestamp, record_status, data_to_be_processed) VALUES(now(), 'TO_BE_PROCESSED', data);
```
You can use the Sender to ingest the data too, the idea is the same.

Then the Reader could execute periodically something like:
```
minTimestamp = previous maxTimestamp + 1;
maxTimestamp = currentTime();
```
```
SELECT timestamp, data_to_be_processed FROM table WHERE record_status = 'TO_BE_PROCESSED' and timestamp >= minTimestamp and timestamp < maxTimeStamp;
```
This would pick the new records up only, because it takes the previous run's `maxTimestamp` as `minTimestamp`.
The Reader sends these tasks to the Writer for processing.

The writer can insert the new status after processing as:
```
INSERT INTO table VALUES(now(), 'PROCESSED', data);
```

Of course, this approach assumes that the clocks of the Producer and the Reader are in sync.
If they run on the same server this should not be a problem.

**Comment by RajvanshR** [comment]
Thank you very much @glasstiger. My Producer Reader and Writer are all in the same process and I will try this out.
