### ISSUE TITLE
A function returning symbol integer representation.

### ISSUE THREAD

**Issue by peter-facko** [questdb/questdb#5098]
### Is your feature request related to a problem?

I am using the SYMBOL datatype in an ID column for its indexing properties.
Since SYMBOL can contain an arbitrary string, I cannot use it as an identifier in places where there are character restrictions such as a URL.

### Describe the solution you'd like.

I propose a function that returns a unique integer for each SYMBOL of a table. The mapping should be stable with respect to table modifications. Different tables can have different symbol representations for the same symbol strings.

Returning the symbol integer representation from the symbol table would comply with this definition.

### Describe alternatives you've considered.

`col + 0` but it was marked as a bug in #5096.

### Full Name:

Peter Fačko

### Affiliation:

Myself

**Comment by abant07** [comment]
Hey @nwoolmer @peter-facko 

I am interested in this issue, could I take it up?

Thanks!
Amogh

**Comment by abant07** [comment]
Hey,

I am about to get started on this issue, but first I did some research over symbols to properly understand what your request is for this feature.

So, from my understanding Symbols are a datatype that will convert strings, that commonly repeats in a database, to an integer. This makes it so that the query latency is much faster because all the unique symbols will be put into an index table where the symbol string is mapped to an integer. 

Then, when a user makes a query that specifies a WHERE clause that filters based on the symbol string given (ie: WHERE id="A", the database engine will convert the string specified in the WHERE clause to an integer, and lookup that integer in the symbol index table to get the rows that it will need to look at in the database to retrieved the columns the user wants.

However, since @peter-facko you have an application where you are passing in an ID (that is a symbol string) into a URL query string parameter (probably because I am guessing you will use this query parameter to do some database query in your backend using the ID for filtering), there is a chance the string that your ID is not URL compatible.

So what you are proposing is you want me to create a function that will allow you to get the specific integer that the symbol string is mapping to in the index table. You will then use this integer in your URL query parameter.

One thing however that I am not able to understand is that you want "Different tables can have different symbol representations for the same symbol strings." Why do you need different representations for same symbol strings if questDB makes separate symbol index tables for each table (or does QuestDB not create separate index tables for different tables? @nwoolmer)

And then another clarification I had is the mapping should be stable with respect to table modifications. What does questDB's symbol table do right now that makes it not stable when the table gets modified? I am a bit new to questDB github, so sorry if this question is a little silly.

Thanks!
Amogh

**Comment by peter-facko** [comment]
Yes, any stable integer is good.

Hashing doesn't work as I need to be able to get a symbol from the ID.

Keeping a mapping table would work.
Exposing the symbol map indexes seemed straightforward, but I didn't realize that they could change.

I don't require symbol representations to be different in different tables, I just don't require them to be the same.
