### ISSUE TITLE
Last column is dropped when query includes an inline addition and a sample by.

### ISSUE THREAD

**Issue by jiteshvassa** [questdb/questdb#5105]
### To reproduce

Given the table definition:
```
CREATE TABLE 'sample_table' (
  name SYMBOL capacity 256 CACHE,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY DAY WAL;
```

When the following is run:
```
SELECT timestamp+60000000 as 'timestamp', 0 AS "extra_column"
FROM sample_table
WHERE name = 'test'
SAMPLE BY (1m);
```

Then the "extra_column" field seems to be lost:
![image](https://github.com/user-attachments/assets/0827d22d-8599-4581-b324-71feefde11da)

Adding an additional column to the select makes the preceding one appear, e.g.:
```
SELECT timestamp+60000000 as 'timestamp', 0 AS "extra_column", 0 AS "extra_column2"
FROM sample_table
WHERE name = 'test'
SAMPLE BY (1m);
```

![image](https://github.com/user-attachments/assets/fb898a16-d960-4bd5-b993-ffda677a4d2f)

If I take out the inline addition being done on the timestamp, then it works as expected:
```
SELECT timestamp as 'timestamp', 0 AS "extra_column", 0 AS "extra_column2"
FROM sample_table
WHERE name = 'test'
SAMPLE BY (1m);
```
![image](https://github.com/user-attachments/assets/7725df02-ddf0-48c4-8caf-d8e13756205d)

Alternatively, if I remove the "sample by" then it also works as expected:
```
SELECT timestamp+60000000 as 'timestamp', 0 AS "extra_column", 0 AS "extra_column2"
FROM sample_table
WHERE name = 'test';
```
![image](https://github.com/user-attachments/assets/90ac7828-801e-47d0-a7eb-59ed50c66695)

Therefore it looks like some combination of doing an inline addition and sample by causes this issue where the last column seems to be silently dropped.

### QuestDB version:

8.1.1

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04 (Docker)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Jitesh Vassa

### Affiliation:

Independent

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by kafka1991** [comment]
@nwoolmer May I work on this issue?
It seems there is a problem in `sqlOptimiser::rewriteSampleBy` after preliminary debugging.

**Comment by kafka1991** [comment]
@nwoolmer 
The root cause of bug is `SAMPLE_BY_REWRITE_WRAP_ADD_TIMESTAMP_COPIES` flag in `sqlOptimiser::rewriteSampleBy`. It's comment in code is:

> [sqlOptimizer.java:L4655]
// Check if there are more aliased timestamp references, e.g.
// `select timestamp a, timestamp b, timestamp c`
// We will remove copies from this model and add them back in the wrapper
The rewriter will remove the `timestamp column` in current `QueryModel` and then readd  the columns in a warper `QueryModel`, but if the `moved timestamp columns` depend on the current's child QueryModel's output column, unexpected behaviours will occur.

However, this flag will cause the bug described in this issue(same name columns in one QueryModel).  This will also cause another unexpected result case:

```
CREATE TABLE 'sample_table10' (
  name SYMBOL capacity 256 CACHE,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY DAY WAL;

insert into sample_table10 values ('AA', '2024-10-29 08:37:35.100');
insert into sample_table10 values ('AA', '2024-10-29 08:37:36.100');
insert into sample_table10 values ('AA', '2024-10-29 08:38:36.100');
insert into sample_table10 values ('AA', '2024-10-29 08:39:36.200');

SELECT timestamp+60000000 as 'timestamp1', 1 AS "extra_column"
FROM sample_table10
WHERE name = 'AA'
SAMPLE BY (1m);


qdb->  timestamp1         | extra_column
----------------------------+--------------
 2024-10-29 08:38:00.000000 |            1
 2024-10-29 08:38:00.000000 |            1
 2024-10-29 08:39:00.000000 |            1
 2024-10-29 08:40:00.000000 |            1
```

The result is not correct and does not conform to the original SQL semantics, The actual QueryModel tree is:

```
QueryModel1[timestamp1 ---> (timestamp+60000000), extra_column] // remove timestamp
    QueryModel2[timestamp1(timestamp+60000000), extra_column, timestamp ---> timefloor(timestamp)] // readd timestamp1
        QueryModel3[timestamp ---> timefloor(timestamp), extra_column]  // remove timestamp1, rewrite sample by to group by
            QueryModel4[timestamp1 ---> (timestamp + 60000000), extra_column]
                QueryModel5[timestamp ---> sample_table10.timestamp, extra_column]
```

In which QueryModel1's timestamp1 function depended `timestamp` is not the original `timestamp` column in sample_table10, but `timefloor(timestamp)` in QueryModel2.

Here I don't understand why rewriter need `SAMPLE_BY_REWRITE_WRAP_ADD_TIMESTAMP_COPIES`? I try to remove the snippet relevant, those cases seems work correctlly.

Can you show me some  cases need `SAMPLE_BY_REWRITE_WRAP_ADD_TIMESTAMP_COPIES` to help me understand.
