### ISSUE TITLE
Using WHERE clause Java Embedded

### ISSUE THREAD

**Issue by dmzayago** [questdb/questdb#610]
I am using the questdb library 5.0.3 in java embedded, but when launching a query with a where it gives me this error

"SELECT * FROM TABLE  WHERE COLUMN = VALUE"

unknown function name: =(INT,INT)

**Comment by bluestreak01** [comment]
We use Java ServiceLoader to load the functions and operators. Unfortunately as of Java 9 service loader uses two different locations to get list of the functions depending on whether or not your project uses Java Modules.

Context of this problem is usually the fact you are not using Java Modules. In this case there are two options:

- copy this file https://github.com/questdb/questdb/blob/master/core/src/test/resources/META-INF/services/io.questdb.griffin.FunctionFactory into your 

```
src/main/resources/META-INF/services/ 
```

directory

or

- use Java Modules
