### ISSUE TITLE
[question] Does QuestDB support percentile aggregation?

### ISSUE THREAD

**Issue by pickledish** [questdb/questdb#704]
I've looked in the docs and wasn't able to find anything aside from the regular aggregations (min, avg, etc), and playing with Postgres syntax for it on `try.questdb.io` suggests that it isn't supported.

Are there plans for this? Could look into something like https://github.com/tdunning/t-digest where intermediate results can be partitioned and merged

**Comment by bluestreak01** [comment]
We can certainly have a look into this if you have interesting usecase for questdb. Our codebase is dependency free, which is why adding t-digest algorithms is a little more complicated affair than using a library. 

Thank you for the pointers though! I am not familar with the algorithm personally but it looks very curious. These are useful papers on the subject:

https://github.com/tdunning/t-digest/blob/master/docs/t-digest-paper/histo.pdf

and impleentation is Facebook folly:

https://github.com/facebook/folly/blob/master/folly/stats/TDigest.h

We should try to understand the algorigth and see if it lends itself to SIMD processing.
